Name:           ros-indigo-pi-trees-ros
Version:        0.1.1
Release:        1%{?dist}
Summary:        ROS pi_trees_ros package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pi_trees
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-pi-trees-lib
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-rospy
BuildRequires:  ros-indigo-catkin

%description
ROS wrappers for the pi_trees_lib Library

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Sep 25 2016 Patrick Goebel <patrick@pirobot.org> - 0.1.1-1
- Autogenerated by Bloom

* Sun Sep 25 2016 Patrick Goebel <patrick@pirobot.org> - 0.1.1-0
- Autogenerated by Bloom

